(function(){
'use strict';
const DB='VehicleRegistrationLookup',VER=1,STORE='datasets',KEY='active',MAX=250;
const state={records:[],dataset:null,activeCategory:'All',query:'',installPrompt:null,selectedRecord:null};
const $=id=>document.getElementById(id),els={fileInput:$('fileInput'),clearBtn:$('clearBtn'),installBtn:$('installBtn'),datasetTitle:$('datasetTitle'),datasetMeta:$('datasetMeta'),importProgress:$('importProgress'),importProgressText:$('importProgressText'),searchInput:$('searchInput'),clearSearchBtn:$('clearSearchBtn'),filterBar:$('filterBar'),resultCount:$('resultCount'),results:$('results'),emptyState:$('emptyState'),limitNote:$('limitNote'),compatBanner:$('compatBanner'),recordDialog:$('recordDialog'),dialogCategory:$('dialogCategory'),dialogName:$('dialogName'),dialogPlate:$('dialogPlate'),dialogFields:$('dialogFields'),dialogFormerBadge:$('dialogFormerBadge'),copyPlateBtn:$('copyPlateBtn'),dialogCloseBtn:$('dialogCloseBtn'),dialogDoneBtn:$('dialogDoneBtn'),toast:$('toast')};
function openDb(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'key'});};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error||new Error('Could not open local database.'));});}
async function dbGet(k){const db=await openDb();return new Promise((res,rej)=>{const tx=db.transaction(STORE,'readonly'),r=tx.objectStore(STORE).get(k);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error);tx.oncomplete=()=>db.close();});}
async function dbPut(v){const db=await openDb();return new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(v);tx.oncomplete=()=>{db.close();res();};tx.onerror=()=>{const e=tx.error;db.close();rej(e);};tx.onabort=tx.onerror;});}
async function dbDelete(k){const db=await openDb();return new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(k);tx.oncomplete=()=>{db.close();res();};tx.onerror=()=>{const e=tx.error;db.close();rej(e);};});}
const norm=v=>String(v||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim(),compact=v=>norm(v).replace(/[^a-z0-9]/g,''),former=r=>norm(r.category)==='former',esc=v=>String(v==null?'':v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function searchData(r){if(r._search)return r._search;const x=Object.values(r.extras||{}).join(' ');return r._search={name:norm(r.name),plate:norm(r.plate),plateCompact:compact(r.plate),sticker:norm(r.stickerNumber),vehicle:norm(r.vehicle),color:norm(r.color),department:norm(r.department),contact:norm(r.contact),parking:norm(r.parkingLot),type:norm(r.registrationType),pay:norm(r.payStatus),category:norm(r.category),extras:norm(x)};}
function tokenScore(r,t){const s=searchData(r),q=norm(t),qc=compact(t);let best=-1;if(qc){if(s.plateCompact===qc)best=130;else if(s.plateCompact.startsWith(qc))best=108;else if(s.plateCompact.includes(qc))best=92;}if(s.name===q)best=Math.max(best,120);else if(s.name.split(' ').some(x=>x.startsWith(q)))best=Math.max(best,98);else if(s.name.includes(q))best=Math.max(best,85);if(s.sticker===q)best=Math.max(best,110);else if(s.sticker.startsWith(q))best=Math.max(best,76);for(const f of [s.vehicle,s.color,s.department,s.contact,s.parking,s.type,s.pay,s.category,s.extras]){if(f===q)best=Math.max(best,58);else if(f.includes(q))best=Math.max(best,42);}return best;}
function recordScore(r,q){const ts=norm(q).split(' ').filter(Boolean);if(!ts.length)return 0;let total=0;for(const t of ts){const s=tokenScore(r,t);if(s<0)return-1;total+=s;}if(!former(r))total+=3;return total;}
function visible(){let a=state.records.filter(r=>state.activeCategory==='All'||r.category===state.activeCategory);if(state.query.trim())a=a.map(r=>({r,s:recordScore(r,state.query)})).filter(x=>x.s>=0).sort((a,b)=>b.s-a.s||norm(a.r.name).localeCompare(norm(b.r.name))).map(x=>x.r);else a=a.slice().sort((a,b)=>Number(former(a))-Number(former(b))||norm(a.name).localeCompare(norm(b.name)));return a;}
function chip(name,count){const b=document.createElement('button');b.type='button';b.className=`filter-chip ${state.activeCategory===name?'active':''} ${norm(name)==='former'?'former':''}`;b.textContent=`${name} · ${count}`;b.onclick=()=>{state.activeCategory=name;renderFilters();renderResults();};return b;}
function renderFilters(){const m=new Map();for(const r of state.records)m.set(r.category,(m.get(r.category)||0)+1);els.filterBar.innerHTML='';els.filterBar.appendChild(chip('All',state.records.length));for(const [name,count] of m)els.filterBar.appendChild(chip(name,count));}
function card(r){const b=document.createElement('button');b.type='button';b.className=`result-card ${former(r)?'former':''}`;const vehicle=[r.color,r.vehicle].filter(Boolean).join(' · '),secondary=r.department||r.registrationType||r.parkingLot||'',sticker=r.stickerNumber?`<span class="sticker-badge">Sticker ${esc(r.stickerNumber)}</span>`:'',fb=former(r)?'<span class="former-badge">Former</span>':'';b.innerHTML=`<div class="result-top"><div><div class="result-name">${esc(r.name||'Unnamed registration')}</div><div class="result-category">${esc(r.category)}</div></div><div class="plate">${esc(r.plate||'NO PLATE')}</div></div><div class="result-meta">${vehicle?`<span>${esc(vehicle)}</span>`:''}${secondary?`<span>${esc(secondary)}</span>`:''}${sticker}${fb}</div>`;b.onclick=()=>showRecord(r);return b;}
function renderResults(){const a=visible();els.results.innerHTML='';els.resultCount.textContent=`${a.length.toLocaleString()} registration${a.length===1?'':'s'}`;els.clearSearchBtn.classList.toggle('hidden',!state.query);if(!state.records.length){els.emptyState.querySelector('h2').textContent='Ready for your registration spreadsheet';els.emptyState.querySelector('p').textContent='Import the current Excel workbook. Searches run locally and can match partial names, plates, sticker numbers, vehicle details, departments, contacts, and parking information.';els.emptyState.classList.remove('hidden');els.limitNote.classList.add('hidden');return;}els.emptyState.classList.toggle('hidden',a.length>0);if(!a.length){els.emptyState.querySelector('h2').textContent='No matching registrations';els.emptyState.querySelector('p').textContent='Try a shorter name or plate fragment, remove a category filter, or search another vehicle detail.';}for(const r of a.slice(0,MAX))els.results.appendChild(card(r));if(a.length>MAX){els.limitNote.textContent=`Showing the first ${MAX} of ${a.length.toLocaleString()} matches. Type more characters to narrow the search.`;els.limitNote.classList.remove('hidden');}else els.limitNote.classList.add('hidden');}
function renderDataset(){if(!state.dataset){els.datasetTitle.textContent='No spreadsheet loaded';els.datasetMeta.textContent='Import an .xlsx file to begin.';return;}els.datasetTitle.textContent=state.dataset.filename||'Vehicle registration database';const d=new Date(state.dataset.importedAt),when=Number.isNaN(d.valueOf())?'':d.toLocaleString();els.datasetMeta.textContent=`${state.records.length.toLocaleString()} records · ${state.dataset.sheets?.length||0} sheets${when?` · Imported ${when}`:''}`;}
function busy(on,text){els.importProgress.classList.toggle('hidden',!on);if(text)els.importProgressText.textContent=text;els.fileInput.disabled=on;els.clearBtn.disabled=on;}
async function processWorkbook(buf,filename){busy(true,'Opening workbook…');try{const p=await XlsxLocalParser.parseXlsx(buf,{onProgress:x=>els.importProgressText.textContent=`Reading ${x.sheetName} (${x.index} of ${x.total})…`}),payload={key:KEY,filename,importedAt:new Date().toISOString(),sheets:p.sheets,warnings:p.warnings,records:p.records};await dbPut(payload);state.dataset=payload;state.records=payload.records;state.activeCategory='All';state.query='';els.searchInput.value='';renderDataset();renderFilters();renderResults();toast(`Imported ${payload.records.length} registrations from ${payload.sheets.length} sheets.`);if(payload.warnings.length){els.compatBanner.textContent=`Imported successfully with ${payload.warnings.length} workbook warning${payload.warnings.length===1?'':'s'}. The searchable registration data was retained.`;els.compatBanner.className='notice notice-warn';}else els.compatBanner.classList.add('hidden');}catch(e){console.error(e);alert(`Spreadsheet import failed. Your previous database was kept unchanged.\n\n${e.message||e}`);}finally{busy(false);els.fileInput.value='';}}
async function importFile(f){if(!f)return;if(!/\.(xlsx|xlsm)$/i.test(f.name)){alert('Please choose an .xlsx or .xlsm Excel workbook.');return;}await processWorkbook(await f.arrayBuffer(),f.name);}
async function clearDb(){if(!state.records.length)return;if(!confirm('Remove the locally saved registration database from this browser?'))return;await dbDelete(KEY);state.records=[];state.dataset=null;state.activeCategory='All';state.query='';els.searchInput.value='';renderDataset();renderFilters();renderResults();toast('Local registration database cleared.');}
function item(label,value){return value?`<div class="detail-item"><div class="label">${esc(label)}</div><div class="detail-value">${esc(value)}</div></div>`:'';}
function showRecord(r){state.selectedRecord=r;els.dialogCategory.textContent=r.category;els.dialogName.textContent=r.name||'Unnamed registration';els.dialogPlate.textContent=r.plate||'—';els.dialogFormerBadge.classList.toggle('hidden',!former(r));let h=[['Sticker #',r.stickerNumber],['Issue date',r.issueDate],['Color',r.color],['Vehicle',r.vehicle],['Department',r.department],['Contact',r.contact],['Type / relation',r.registrationType],['Parking lot',r.parkingLot],['Pay status',r.payStatus],['Source row',r.sourceRow?String(r.sourceRow):'']].map(x=>item(x[0],x[1])).join('');for(const [k,v] of Object.entries(r.extras||{}))h+=item(k,v);els.dialogFields.innerHTML=h||item('Record','No additional fields');els.copyPlateBtn.disabled=!r.plate;if(typeof els.recordDialog.showModal==='function')els.recordDialog.showModal();else alert(`${r.name}\nPlate: ${r.plate}`);}
async function copyPlate(){const p=state.selectedRecord?.plate;if(!p)return;try{await navigator.clipboard.writeText(p);toast(`Copied plate ${p}`);}catch{prompt('Copy plate:',p);}}
let tt;function toast(m){clearTimeout(tt);els.toast.textContent=m;els.toast.classList.add('show');tt=setTimeout(()=>els.toast.classList.remove('show'),2600);}
function pwa(){if('serviceWorker'in navigator&&(location.protocol==='https:'||location.hostname==='localhost'||location.hostname==='127.0.0.1'))navigator.serviceWorker.register('sw.js').catch(console.warn);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.installPrompt=e;els.installBtn.classList.remove('hidden');});window.addEventListener('appinstalled',()=>{state.installPrompt=null;els.installBtn.classList.add('hidden');toast('Vehicle Lookup installed.');});els.installBtn.onclick=async()=>{if(!state.installPrompt)return;state.installPrompt.prompt();await state.installPrompt.userChoice;state.installPrompt=null;els.installBtn.classList.add('hidden');};}
async function init(){if(!('indexedDB'in window)){els.compatBanner.textContent='This browser cannot save the registration database locally. Use current Chrome or Edge.';els.compatBanner.className='notice notice-warn';}else if(location.protocol==='file:'){els.compatBanner.textContent='Browser-test mode: spreadsheet import and search work here, but installing the PWA/offline shell requires HTTPS or localhost.';els.compatBanner.className='notice notice-info';}try{const s=await dbGet(KEY);if(s?.records){state.dataset=s;state.records=s.records;}}catch(e){console.warn(e);}renderDataset();renderFilters();renderResults();pwa();}
els.fileInput.onchange=e=>importFile(e.target.files?.[0]);els.clearBtn.onclick=clearDb;els.searchInput.oninput=e=>{state.query=e.target.value;renderResults();};els.clearSearchBtn.onclick=()=>{els.searchInput.value='';state.query='';renderResults();els.searchInput.focus();};els.dialogCloseBtn.onclick=()=>els.recordDialog.close();els.dialogDoneBtn.onclick=()=>els.recordDialog.close();els.copyPlateBtn.onclick=copyPlate;els.recordDialog.onclick=e=>{if(e.target===els.recordDialog)els.recordDialog.close();};
init();
})();
