(function(global){
'use strict';
const td=new TextDecoder('utf-8'),COL_LIMIT=32;
const u16=(v,o)=>v.getUint16(o,true),u32=(v,o)=>v.getUint32(o,true);
function findEocd(v){const min=Math.max(0,v.byteLength-65557);for(let i=v.byteLength-22;i>=min;i--)if(u32(v,i)===0x06054b50)return i;throw new Error('This file does not appear to be a valid .xlsx ZIP container.');}
function parseZip(buf){const v=new DataView(buf),e=findEocd(v),disk=u16(v,e+4),cdisk=u16(v,e+6),count=u16(v,e+10),coff=u32(v,e+16);if(disk||cdisk||count===65535||coff===0xffffffff)throw new Error('ZIP64 or multi-disk Excel files are not supported by this lightweight importer.');const files=new Map();let p=coff;for(let i=0;i<count;i++){if(u32(v,p)!==0x02014b50)throw new Error('Excel ZIP directory is damaged or unsupported.');const method=u16(v,p+10),cs=u32(v,p+20),us=u32(v,p+24),nl=u16(v,p+28),el=u16(v,p+30),cl=u16(v,p+32),lo=u32(v,p+42),name=td.decode(new Uint8Array(buf,p+46,nl)).replace(/\\/g,'/');files.set(name,{method,compressedSize:cs,uncompressedSize:us,localOffset:lo});p+=46+nl+el+cl;}return{buf,v,files};}
async function inflate(bytes){if(typeof DecompressionStream!=='function')throw new Error('This browser is too old to read compressed .xlsx files. Use a current Chrome or Edge browser.');const s=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('deflate-raw'));return new Uint8Array(await new Response(s).arrayBuffer());}
async function zipBytes(z,path){const e=z.files.get(path);if(!e)return null;const o=e.localOffset;if(u32(z.v,o)!==0x04034b50)throw new Error('Invalid ZIP entry: '+path);const nl=u16(z.v,o+26),el=u16(z.v,o+28),start=o+30+nl+el,c=new Uint8Array(z.buf,start,e.compressedSize);if(e.method===0)return c.slice();if(e.method===8)return inflate(c);throw new Error('Unsupported Excel compression method ('+e.method+').');}
async function zipText(z,path,required){const b=await zipBytes(z,path);if(!b){if(required)throw new Error('Required Excel component is missing: '+path);return null;}return td.decode(b);}
function unescapeXml(s){return String(s||'').replace(/&#(x?[0-9a-f]+);|&(amp|lt|gt|quot|apos);/gi,(m,num,named)=>{if(num){const hex=num[0].toLowerCase()==='x';const n=parseInt(hex?num.slice(1):num,hex?16:10);return Number.isFinite(n)?String.fromCodePoint(n):m;}return({amp:'&',lt:'<',gt:'>',quot:'"',apos:"'"})[named.toLowerCase()]||m;});}
function getAttr(tag,name,allowPrefix){const n=name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),p=allowPrefix?'(?:[A-Za-z_][\\w.-]*:)?':'';const m=new RegExp('(?:^|\\s)'+p+n+'\\s*=\\s*(["\'])([\\s\\S]*?)\\1','i').exec(tag);return m?unescapeXml(m[2]):null;}
function resolvePath(base,target){if(target.startsWith('/'))return target.slice(1);const p=base.split('/');p.pop();for(const part of target.split('/')){if(!part||part==='.')continue;if(part==='..')p.pop();else p.push(part);}return p.join('/');}
function colNum(ref){const m=/^([A-Z]+)\d+$/i.exec(ref||'');if(!m)return null;let n=0;for(const c of m[1].toUpperCase())n=n*26+c.charCodeAt(0)-64;return n;}
function textNodes(xml,tag='t'){let s='',re=new RegExp('<'+tag+'\\b[^>]*>([\\s\\S]*?)<\\/'+tag+'>','gi'),m;while((m=re.exec(xml)))s+=unescapeXml(m[1].replace(/<[^>]+>/g,''));return s;}
function sharedStringsFrom(xml){const a=[];if(!xml)return a;const re=/<si\b[^>]*>([\s\S]*?)<\/si>/gi;let m;while((m=re.exec(xml)))a.push(textNodes(m[1],'t'));return a;}
function cellValue(attrs,body,shared){const t=getAttr(attrs,'t',false)||'';if(t==='inlineStr')return textNodes(body,'t');const vm=/<v\b[^>]*>([\s\S]*?)<\/v>/i.exec(body);if(!vm)return'';const raw=unescapeXml(vm[1].trim());if(t==='s'){const i=Number(raw);return Number.isInteger(i)&&shared[i]!=null?shared[i]:raw;}if(t==='b')return raw==='1'?'TRUE':'FALSE';return raw;}
function normHeader(x){return String(x||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/&/g,' and ').replace(/[^a-z0-9#]+/g,' ').trim();}
const aliases={'#':'stickerNumber','sticker':'stickerNumber','sticker #':'stickerNumber','sticker number':'stickerNumber','permit':'stickerNumber','permit #':'stickerNumber','name':'name','employee name':'name','resident name':'name','issue date':'issueDate','date issued':'issueDate','issued date':'issueDate','plate':'plate','license plate':'plate','lic plate':'plate','plate number':'plate','color':'color','vehicle color':'color','make model':'vehicle','vehicle make':'vehicle','vehicle make model':'vehicle','make':'vehicle','vehicle':'vehicle','department':'department','dept':'department','contact':'contact','phone':'contact','phone number':'contact','parking lot':'parkingLot','parking':'parkingLot','lot':'parkingLot','pay status':'payStatus','payment status':'payStatus','employee visitor ss':'registrationType','employee visitor':'registrationType','type':'registrationType'};
const HEADER_ALIASES=new Map(Object.entries(aliases).map(([k,v])=>[normHeader(k),v]));
function dateText(v,date1904){const n=Number(v);if(!Number.isFinite(n)||n<1||n>100000)return String(v||'').trim();const epoch=date1904?Date.UTC(1904,0,1):Date.UTC(1899,11,30),d=new Date(epoch+Math.floor(n)*86400000);if(Number.isNaN(d.valueOf()))return String(v||'').trim();return new Intl.DateTimeFormat('en-US',{month:'2-digit',day:'2-digit',year:'numeric',timeZone:'UTC'}).format(d);}
function rowsFrom(xml,shared){const out=[],rowRe=/<row\b([^>]*)>([\s\S]*?)<\/row>/gi;let rm;while((rm=rowRe.exec(xml))){const rn=Number(getAttr(rm[1],'r',false)||out.length+1),cells=new Map(),body=rm[2],cellRe=/<c\b([^>]*?)(?:\/\s*>|>([\s\S]*?)<\/c>)/gi;let cm;while((cm=cellRe.exec(body))){const ref=getAttr(cm[1],'r',false),col=colNum(ref);if(!col||col>COL_LIMIT)continue;const v=cellValue(cm[1],cm[2]||'',shared);if(v!=='')cells.set(col,v);}if(cells.size)out.push({rowNumber:rn,cells});}return out;}
function detectHeader(rows){let best=null;for(const r of rows.slice(0,12)){const mappings=new Map();let recognized=0;for(const [col,val] of r.cells){const key=HEADER_ALIASES.get(normHeader(val));if(key){mappings.set(col,key);recognized++;}}const imp=new Set(mappings.values()),score=recognized+(imp.has('name')?2:0)+(imp.has('plate')?2:0)+(imp.has('stickerNumber')?1:0);if(recognized>=3&&(!best||score>best.score))best={rowNumber:r.rowNumber,mappings,score,raw:r};}return best;}
const clean=x=>String(x==null?'':x).replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim();
function recordsFrom(sheetName,rows,h,date1904){const records=[],headerNames=new Map();for(const [c,v] of h.raw.cells)headerNames.set(c,clean(v));for(const row of rows){if(row.rowNumber<=h.rowNumber)continue;const r={category:sheetName,sourceRow:row.rowNumber,stickerNumber:'',name:'',issueDate:'',plate:'',color:'',vehicle:'',department:'',contact:'',parkingLot:'',payStatus:'',registrationType:'',extras:{}};let mapped=0;for(const [c,v0] of row.cells){const v=clean(v0);if(!v)continue;const f=h.mappings.get(c);if(f){r[f]=f==='issueDate'?dateText(v,date1904):v;mapped++;}else{const label=headerNames.get(c);if(label&&normHeader(label))r.extras[label]=v;}}if(!mapped)continue;if(!(r.name||r.plate||r.stickerNumber||r.vehicle||r.department||r.registrationType))continue;records.push(r);}return records;}
function workbookInfo(xml){const date1904=/<workbookPr\b[^>]*\bdate1904\s*=\s*(["'])1\1/i.test(xml),sheets=[],re=/<sheet\b([^>]*?)\/?\s*>/gi;let m;while((m=re.exec(xml))){const name=getAttr(m[1],'name',false),rid=getAttr(m[1],'id',true);if(name&&rid)sheets.push({name:clean(name),rid});}return{date1904,sheets};}
function relationships(xml){const map=new Map(),re=/<Relationship\b([^>]*?)\/?\s*>/gi;let m;while((m=re.exec(xml))){const id=getAttr(m[1],'Id',false),target=getAttr(m[1],'Target',false);if(id&&target)map.set(id,target);}return map;}
async function parseXlsx(buf,opts={}){if(!(buf instanceof ArrayBuffer))throw new Error('Expected an Excel file.');const z=parseZip(buf),wxml=await zipText(z,'xl/workbook.xml',true),rxml=await zipText(z,'xl/_rels/workbook.xml.rels',true),shared=sharedStringsFrom(await zipText(z,'xl/sharedStrings.xml',false)),wi=workbookInfo(wxml),rels=relationships(rxml),records=[],sheets=[],warnings=[];for(let i=0;i<wi.sheets.length;i++){const s=wi.sheets[i],target=rels.get(s.rid);if(!target){warnings.push(s.name+': worksheet relationship missing');continue;}opts.onProgress?.({phase:'sheet',index:i+1,total:wi.sheets.length,sheetName:s.name});const txt=await zipText(z,resolvePath('xl/workbook.xml',target),false);if(!txt){warnings.push(s.name+': worksheet data missing');continue;}const rows=rowsFrom(txt,shared),h=detectHeader(rows);if(!h){warnings.push(s.name+': recognizable registration headers were not found');continue;}const sr=recordsFrom(s.name,rows,h,wi.date1904);records.push(...sr);sheets.push({name:s.name,records:sr.length,headerRow:h.rowNumber});await new Promise(r=>setTimeout(r,0));}if(!records.length)throw new Error('No vehicle registration records were found. Check that the workbook uses the expected registration columns.');return{records,sheets,warnings,date1904:wi.date1904};}
global.XlsxLocalParser={parseXlsx,normalizeHeader:normHeader,excelSerialToDateText:dateText};
})(typeof window!=='undefined'?window:globalThis);
